services:
  db:
    image: postgres:14.3
    restart: unless-stopped  # Better restart policy
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: mealproductsdb
    volumes:
      - type: bind
        source: ./postgres
        target: /var/lib/postgresql/data
        consistency: delegated  # Important for MacOS performance